2022-11-11 16:57:14,949 MainThread udi_interface      INFO     polylogger:set_basic_config: set_basic_config: enable=True level=30
2022-11-11 16:57:15,747 MainThread udi_interface      INFO     __init__:<module>: UDI Python Interface for Polyglot version 3 3.0.15 Starting...
2022-11-11 16:57:16,037 MainThread udi_interface      DEBUG    tuya-test:<module>: Staring Tuya Interface
2022-11-11 16:57:16,037 MainThread udi_interface.interface CRITICAL interface:__init__: Failed to parse init. Exiting...
2022-11-11 16:57:16,037 MainThread udi_interface      ERROR    udi_interface:write: Traceback (most recent call last):
2022-11-11 16:57:16,037 MainThread udi_interface      ERROR    udi_interface:write: File "/Users/stevenbailey/.pyenv/versions/tiny_tuya_3.7.7_clean/lib/python3.7/site-packages/udi_interface/interface.py", line 130, in __init__
2022-11-11 16:57:16,037 MainThread udi_interface      ERROR    udi_interface:write: base64.b64decode(os.environ.get('PG3INIT')))
2022-11-11 16:57:16,037 MainThread udi_interface      ERROR    udi_interface:write: File "/Users/stevenbailey/.pyenv/versions/3.7.7/lib/python3.7/base64.py", line 80, in b64decode
2022-11-11 16:57:16,047 MainThread udi_interface      ERROR    udi_interface:write: s = _bytes_from_decode_data(s)
2022-11-11 16:57:16,047 MainThread udi_interface      ERROR    udi_interface:write: File "/Users/stevenbailey/.pyenv/versions/3.7.7/lib/python3.7/base64.py", line 46, in _bytes_from_decode_data
2022-11-11 16:57:16,047 MainThread udi_interface      ERROR    udi_interface:write: "string, not %r" % s.__class__.__name__) from None
2022-11-11 16:57:16,047 MainThread udi_interface      ERROR    udi_interface:write: TypeError
2022-11-11 16:57:16,047 MainThread udi_interface      ERROR    udi_interface:write: :
2022-11-11 16:57:16,047 MainThread udi_interface      ERROR    udi_interface:write: argument should be a bytes-like object or ASCII string, not 'NoneType'
2022-11-11 16:57:16,048 MainThread udi_interface      ERROR    udi_interface:write: During handling of the above exception, another exception occurred:
2022-11-11 16:57:16,048 MainThread udi_interface      ERROR    udi_interface:write: Traceback (most recent call last):
2022-11-11 16:57:16,048 MainThread udi_interface      ERROR    udi_interface:write: File "/Users/stevenbailey/UDI Development PG3/udi-tuya-poly-james-play/tuya-test.py", line 21, in <module>
2022-11-11 16:57:16,048 MainThread udi_interface      ERROR    udi_interface:write: polyglot = udi_interface.Interface([TuyaController, TuyaNode])
2022-11-11 16:57:16,048 MainThread udi_interface      ERROR    udi_interface:write: File "/Users/stevenbailey/.pyenv/versions/tiny_tuya_3.7.7_clean/lib/python3.7/site-packages/udi_interface/interface.py", line 133, in __init__
2022-11-11 16:57:16,048 MainThread udi_interface      ERROR    udi_interface:write: sys.exit(1)
2022-11-11 16:57:16,048 MainThread udi_interface      ERROR    udi_interface:write: SystemExit
2022-11-11 16:57:16,048 MainThread udi_interface      ERROR    udi_interface:write: :
2022-11-11 16:57:16,048 MainThread udi_interface      ERROR    udi_interface:write: 1
2022-11-11 16:57:16,048 MainThread udi_interface      ERROR    udi_interface:write: During handling of the above exception, another exception occurred:
2022-11-11 16:57:16,048 MainThread udi_interface      ERROR    udi_interface:write: Traceback (most recent call last):
2022-11-11 16:57:16,048 MainThread udi_interface      ERROR    udi_interface:write: File "/Users/stevenbailey/UDI Development PG3/udi-tuya-poly-james-play/tuya-test.py", line 27, in <module>
2022-11-11 16:57:16,048 MainThread udi_interface      ERROR    udi_interface:write: polyglot.stop()
2022-11-11 16:57:16,048 MainThread udi_interface      ERROR    udi_interface:write: NameError
2022-11-11 16:57:16,048 MainThread udi_interface      ERROR    udi_interface:write: :
2022-11-11 16:57:16,048 MainThread udi_interface      ERROR    udi_interface:write: name 'polyglot' is not defined
